FORMAT: 1A

# Annex Test API
Annex Test API is a inventory management synchronization service


## Item Retrieval [/1.0/resources/catalog/item{?barcode,auth_token}]

### Item retrieved [GET]

+ Parameters
    
    + barcode (required, number) ... The scanned barcode of an individual item
    
        + Values
            + `4567329801`
    
    + auth_token (required, string) ... Required auth token for security purposes
    
        + Values
            + `QT853UT9hkj23`


+ Response 200 (application/json)

        {
            "item_id": 123456789,
            "bib_id": 987654321,
            "isbn": 543216789,
            "issn": "",
            "title": "Hartzler's Guide to Eternal Wisdom",
            "author": "Jonathan Hartzler",
            "pub_date": "2014",
            "volume": ""
        }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
